path: "data/raw/urban_tree_dataset"
split: "train"
batch_size: 2
num_workers: 0
device: "mps"  
model: "gaussian" 
spectral_norm: False
lr: 1e-3
weight_decay: 1e-5
kl_weight: 1e-1
max_grad_norm: 1.0
latent_dim: 128
residual: False
num_steps: 10
beta_1: 0.9
beta_T: 0.999
sched_mode: "linear"