# Dataset parameters
data_path:
- "data"
- "processed"
- "urban_tree_dataset"
transform:
train_split: 0.8
val_split: 0.1
test_split: 0.1

# Training parameters
epochs: 200
batch_size: 64
lr: 1e-3
weight_decay: 1e-5
kl_weight: 1e-1
patience: 5
delta: 1e-2

# Autoencoder parameters
latent_dim: 128
residual: false

# Flow VAE parameters
latent_flow_depth: 2
latent_flow_hidden_dim: 128

# Variance scheduler parameters
num_steps: 10
beta_1: 0.9
beta_T: 0.999
sched_mode: "linear"

# Model parameters
device: "cuda"
model: "flow"
seed: 32
num_workers: 0
max_grad_norm: 1.0
spectral_norm: false

# Save path
experiment_dir: "./outputs"

debug: false
hydra:
  run:
    dir: ./outputs\2025-01-23-13-39
